const options = {
  openapi: null, // Enable/Disable OpenAPI. By default is null
  language: 'en-US', // Change response language. By default is 'en-US'
  disableLogs: false, // Enable/Disable logs. By default is false
  autoHeaders: true, // Enable/Disable automatic headers capture. By default is true
  autoQuery: true, // Enable/Disable automatic query capture. By default is true
  autoBody: true, // Enable/Disable automatic body capture. By default is true
};

const swaggerAutogen = require('swagger-autogen')(options);

const outputFile = './swagger.json';
const endpointsFiles = ['./routes/record.routes'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Jolifox API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Record',
      description: 'Endpoints',
    },
  ],
};

swaggerAutogen(outputFile, endpointsFiles, doc);
